# Generated by Django 5.2 on 2025-04-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254)),
                ('pnumber', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=245)),
                ('city', models.CharField(max_length=233)),
                ('state', models.CharField(choices=[('UP', 'Uttar Pradesh'), ('MH', 'Maharashtra'), ('DL', 'Delhi'), ('RJ', 'Rajasthan'), ('BH', 'Bihar')], max_length=2)),
                ('zip', models.IntegerField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
