# Generated by Django 5.2 on 2025-07-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='Addres',
        ),
    ]
