# Generated by Django 5.2 on 2025-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_address_address_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='FullName',
            field=models.CharField(max_length=100),
        ),
    ]
