# Generated by Django 5.2 on 2025-07-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_address_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Addres',
            new_name='Add',
        ),
    ]
