# Generated by Django 5.2 on 2025-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='MobileNumber',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
