# Generated by Django 5.2 on 2025-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_address_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
